spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/factoryvision
    username: gaeul
    password: 1234

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL14Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8080

jwt:
  issuer: moonga10@naver.com
  secretKey: secretKey