spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/factoryvision
    username: gaeul
    password: 1234

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL14Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true

  security:
    user:
      password: 1

  data:
    redis:
      port: 6379
      host: localhost
      timeout: 3000

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8080

jwt:
  issuer: moonga10@naver.com
  secretKey: secretKey

#springdoc:
#  swagger-ui:
#    path: /swagger.html
#    groups-order: DESC
#  api-docs:
#    paths-to-match:
#      - /**

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: /
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    groups:
      enabled: true

