version: '3'

services:

  spring-app:
    container_name: spring-app
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - network

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: factoryvision
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
#    restart: always
    networks:
      - network


  redis:
    image: redis:latest
    container_name: redis
    ports:
       - "6379:6379"
    networks:
       - network

volumes:
  postgres-db-volume:

networks:
  network:
    driver: bridge