version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: factoryvision
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-db-volume: